// This file is auto-generated by TanStack Router
// Do not edit this file manually

import { createFileRoute } from '@tanstack/react-router'
import { Dashboard } from './routes/index'
import { AccountsPage } from './routes/accounts'
import { TransactionsPage } from './routes/transactions'
import { AllocationsPage } from './routes/allocations'
import { Layout } from './components/Layout'

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': typeof import('./routes/index.tsx')['Route']
    '/accounts': typeof import('./routes/accounts.tsx')['Route']
    '/transactions': typeof import('./routes/transactions.tsx')['Route']
    '/allocations': typeof import('./routes/allocations.tsx')['Route']
  }
}

export const routeTree = createFileRoute('/')({
  component: Layout,
  children: [
    {
      path: '/',
      component: Dashboard,
    },
    {
      path: '/accounts',
      component: AccountsPage,
    },
    {
      path: '/transactions',
      component: TransactionsPage,
    },
    {
      path: '/allocations',
      component: AllocationsPage,
    },
  ],
})
