"""baseline schema

Revision ID: d22347b47173
Revises: 
Create Date: 2025-11-08 22:02:22.510532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22347b47173'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('currency', sa.Enum('PHP', 'USD', 'EUR', 'GBP', 'JPY', 'AUD', 'CAD', 'CHF', 'CNY', 'SGD', name='currencytype'), nullable=False))
    op.add_column('accounts', sa.Column('days_until_due_date', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('projected_amount', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('projected_currency', sa.Enum('PHP', 'USD', 'EUR', 'GBP', 'JPY', 'AUD', 'CAD', 'CHF', 'CNY', 'SGD', name='currencytype'), nullable=True))
    op.add_column('transactions', sa.Column('original_amount', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('original_currency', sa.Enum('PHP', 'USD', 'EUR', 'GBP', 'JPY', 'AUD', 'CAD', 'CHF', 'CNY', 'SGD', name='currencytype'), nullable=True))
    op.add_column('transactions', sa.Column('exchange_rate', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('transfer_fee', sa.Float(), nullable=False))
    op.add_column('transactions', sa.Column('is_posted', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('transfer_from_account_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('transfer_to_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'accounts', ['transfer_to_account_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'accounts', ['transfer_from_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'transfer_to_account_id')
    op.drop_column('transactions', 'transfer_from_account_id')
    op.drop_column('transactions', 'is_posted')
    op.drop_column('transactions', 'transfer_fee')
    op.drop_column('transactions', 'exchange_rate')
    op.drop_column('transactions', 'original_currency')
    op.drop_column('transactions', 'original_amount')
    op.drop_column('transactions', 'projected_currency')
    op.drop_column('transactions', 'projected_amount')
    op.drop_column('accounts', 'days_until_due_date')
    op.drop_column('accounts', 'currency')
    # ### end Alembic commands ###
